var title = document.getElementById('title');
title.innerHTML = "December 2023";

var date = new Date();
var month = 12;
var year = 2023;
var christmasDay = 25;
var today = date.getDate();

var calendar = document.getElementById('calendar');


// Find out which day of the week December 1st, 2023 falls on
var firstDay = new Date(year, month - 1, 1).getDay();

// Create empty divs for the days before December 1st
for (var i = 0; i < firstDay; i++) {
    var emptyDay = document.createElement('div');
    emptyDay.classList.add('day');
    calendar.appendChild(emptyDay);
}


// Pre-defined notes for each day
var notes = {
    1: "HEHEHEHE THIS IS A BIT LATE BUT HEYYY WELCOME TO MY RANDOMNESS AND THIS WILL BE THE LITTLE SURPRISE I HAVE FOR YOU IN THIS BEAUTIFUL MONTH CALLED DECEMBER <3",
    2: "THIS IS ALSO A BIT LATE BUT HEYYYYYYY IT'S OKAYYY, HAPPY 10 MONTHS BBYYYYY, IK THINGS HAS BEEN HARD LATELY BUT I'M SO PROUD OF YOU FOR NEVER GIVING UP I KNOW YOU'RE BUSY AND THAT'S OKAY I WON'T MAKE IT HARD FOR YOU AS WELL ALL I ASK FOR IS THAT YOU TAKE CARE OF URSELF WELL ENOUGH OK? OK GBOLEH G OK ANYWAYS I HOPE I GET TO MAKE MORE THINGS AND TELL YOU ALL THIS AGAIN NEXT MONTH HEHEHEHHEHE",
    3: "HELLO BBYYY I JUST WANT TO LET YOU KNOW THAT I LOVE YOU SO MUCH THANK YOU FOR BEING SUCH  A WONDERFUL PERSON AND THANK YOU FOR COMING INTO MY LIFE I LOVE YOUUU",
    4: "YOYOYOYO IS UR FUTURE HUSBAND SPEAKING AND THIS IS JUST A FRIENDLY REMINDER THAT I ALSO WANT UT ATTENTION HEHEHEH AND ALSO DONT FORGET TO EAT AND DRINK ENOUGH OK? OK GOOD I LOVE YOU MWUAH MWAUH MWUAH",
    5: "GOODLUCK WITH YOUR EXAMSS BEBIIII MWUAHHHHHH I KNOW U GOT THISSS",
    6: "BEBIIIIII I LOVE YOUU DO UR BEST TODAY AS WELL I KNOW YOU GOT THIS You ALWAY DOOO I LOVE YOUUU MY LOVE GIVE IT UR ALL REGARDLESS OF WHAT HAPPENS I AM ALWAYS PROUD OF U LOVE",
    7: "HELLO DUMPLING, I JUST WANTED TO CHECK IN AND SAY I LOVE YOUO MY DEAR DON'T EVER FORGET THAT AND ALSO MAKE SURE THAT YOU'RE NOT STRESSING URSELF OUT TOO MUCH INGET YA AS LONG AS U KEEP TRYING TO GIVE UR ALL YOU WILL ALWAYS IMPROVE TO BE BETTER HEHEHE MWUAHHH",
    8: "HAVE A SAFE FLIGHT SYGGGGG I LOVE YOUUUU I KNOW YOU DESERVE THIS HOLIDAY VERY MUCH I LOVE YOUUUUU NEVER HESITATE TO CALL ME EVEN IF IT IS EARLY IN THE MORNING FOR MEEEE MWUAHHHHHHHHH",
    9: "ITS A SATURDAY FOR MEEE AND IT'S PROBS A FRIDAY FOR YOUU IK U GON BE VERY BUSY BUT ITS OKAY I'M J HERE TO REMIND YOU THAT DESPITE ME ALSO BEING BUSY IF U CALL ME OR TEXT ME I'D RESPOND ASAP BECAUSE UR MY P R I O R I T Y YEAH MY PRIORITY LOF BEBI",
    10: "WELL TODAY IS THE LAST DAY FOR ME AT LEAST IDK FOR U BUT YEAH TODAY IS THE LAST DAY U CAN SEE THESE TEXTS HEHEHHEHE OFC UNTIL TOMORROW BARU BS BUT YOU GET WHAT I MEAN SO FROM THIS POINT ONWARDS ALL OF THESE ARE NOW A LIL SURPRISE FOR EVERY SINGLE DAY HAVE FUN DEAR THINK OF IT AS A SMALL EARLY CHRISTMAS GIFT",
    11: "WELL FOR ME THIS IS A MONDAY BUT I'M SURE ITS A SUNDAY FOR YOU ANYWAYS REMEMBER THIS YA NEVER EVER AND I MEAN EVER DOUBT URSELF OR DEGRADE URSELF BECAUSE U ARE AMAZING THE WAY YOU ARE IF U CHANGED THEN THAT WOULDN'T BE MY BEAUTIFUL AND UNIQUE BBY, MHM I LOVE YOU FOR WHO YOU ARE NEVER FORGET THAT",
    12: "HELLO BBYYY HOW IS UR DAY GOING? I HOPE ITS GOING GREAT IF IT ISN'T COME LET ME KNOW I WANNA HEAR ALL ABOUT IT I'LL LISTEN TO ALL OF IT WHILE I HOLD YOU UTUTUTUTUTUU COME HERE MY SWEET LITTLE GIRL",
    13: "BBYYYY BEBIIII DUMPLINGGG SWEETHEARTT LOVEEEE HONEYYYY I LOVE YOU THAT'S ALL I WANTED TO SAY AND NO I LOVE YOU MOST THAT'S FINAL HEHEHHEHEH MWUAH I LOF U",
    14: "(QUEUE MOANA SONG) WHAT CAN I SAYYYYY EXCEPTTT I LOVE YOUUUU I LOVE YOUUU SOOO GOD DAMN MUCH I JUST ABSOLUTELY LOVE YOU I REALLY REALLY REALLYYYYYYYY LOVE YOUUUU",
    15: "IT IS CURRENTLY 15 OF DECEMBER MEANINGGG WE ARE TECHNICALLY HALF WAY THROUGH DECEMBER ALREADY NOW GIVE URSELF A PAT ON THE BACK FOR GETTING THIS FAR THROUGH DECEMBER AND IN ABOUT 15/16 DAYS IT'LL BE NEW YEARSSSSS LETS GOOOOOO A STEP CLOSER TO MEETING MY GORGEOUS GIRL",
    16: "HELLOO IT IS 16TH OF DECEMBER AND THIS IS JUST A FRIENDLY REMINDER THAT I STILL WANT UR ATTENTION I MIGHT BE BUSY BUT WHO CARES DISTURB ME TALK TO ME MAKE ME LAUGH ANYTHING IS OK AS LONG AS UR THE ONE DOING IT HEHEHHEHEE I LOVE YOU SO MUCH",
    17: "HELLO HELLO MY NAME'S DIBO HERE IS SOMETHING YOU SHOULD KNOW WHEN YOU WANT A GIFT SAY THIS! I LOVE LIKS SO MUCH HEHEHEHEHE GOTCHU I KNEW IT U SAID IT HEHEHE EI LOVE YOU TOOO MWUAH",
    18: "IT IS OFFICIALLY A WEEK TILL CHRISTMASS MEANINGG IT'S TIME FOR CHRISTMASS SONGGSSSSSS SOOOOOO ITS BEGINNINGGG TO LOOK A LOT LIKE CHRISTMASSSSSS AND THIS CHRISTMASSS I HAVE THE MOST WONDERFUL AND BEAUTIFUL GIRLFRIEND EVER HER NAME IS ELEJI SHE IS MY FUTURE WIFEY HEHEHHEE",
    19: "IT IS OFFICIALLY 6 DAYS TILL CHRISTMASS MEANINGGGG WE GON BE A STEP CLOSER TO OUR GOALSSS AND ITS THE BEST FUCKING SEASON EVERRRRR",
    20: "IT IS OFFICIALLY 5 DAYS TILL CHRISTMAS WHICH ALSO MEANS THAT I AM GOING TO LOVE YOU THROUGH ANOTHER CHRISTMAS AGAIN HOHOHOHO THIS MEANS I HAVE LOVED U FOR 2 CHRISTMASES SOON",
    21: "IT IS NOW OFFICIALLY 4 DAYS TILL CHRISTMAS WHICH MEANS IT IS ALMOST TIME FOR ME TO SING RANDOM CHRISTMAS SONGS (NOT LIKE I HAVEN'T BEEN DOING THAT SINCE THE START OF DECEMBER) UNTIL YOU'RE BORED AND TIRED OF ME HEHEHHE I LOVE YOU DON'T GET TIRED OF ME",
    22: "NOW IT IS OFFICIALLY 3 DAYS TILL CHRISTMAS EACH DAY WE GET CLOSER TO CHRISTMAS LIKE HOW EACH DAY MY LOVE FOR YOU JUST KEEPS ON GETTING BIGGER AND BIGGER HEHEHEHEHE I LOVE YOU",
    23: "YOYOYOYOYO IT'S OFFICIALLY 2 DAYS TILL CHRISTMASS MEANINGGG I HAVE 2 THINGS TO TELL YOU 1 IS THE USUAL I LOVE YOU SO FUCKING MUCH AND 2 IS THAT US 2 ARE MEANT TO BE TOGETHER 4 EVER HEHEHHEHE I SO KEWL WITH PUNS",
    24: "BRO ITS LEGIT 1 MORE DAY TILL CHRISTMAS LIKE TOMORROW IS CHRISTMAS LIKE DAMN MAN YK WHAT THAT MEANS? YESSIR GET UR ASS UP IT'S TIME TO HUNT A BIG ASS JOLLY MAN THAT SNEAKS INTO MY HOUSE EVERY YEAR TO PUT PRESENTS I MEAN IF WE CAN CATCH HIM WE GET UNLIMITED GIFTS (300 IQ MOMENT) HEHEHHEEHE I LOVE YOUUUUUU",
    25: "Merry Christmas my beautiful girl!, i'm sad i can't spend this christmas with you this time but it's okay as long as you're healthy and safe i am more than happy enough already, anyways thank you for being such a wonderful person i absolutely love you and i am forever grateful for you i do wish that i can at least send you some stuff for christmas though i'm not sure yet but if i can i will HEHEHHEHE if i can't then expect some more surprises from me anyways last but not least i just wanna say that i hope next year i'll at least be able to give you a better surprise than this year and i hope that you won't get tired of me yet HEHEHEH i love you my beautiful girl mwuahh",
    26: "CHRISTMASS HAS OFFICIALLY COME TO AN END BUT YK WHAT WON'T COME TO AN END? THAT'S RIGHT MY LOVE FOR YOU <3",
    27: "WELL NOT THAT CHRISTMAS IS BASICALLY DONE WE CAN NOW LOOK FORWARD TO NEW YEARS BECAUSE NEW YEAR NEW REASON TO LOVE ELEJI HEHEHHEE",
    28: "IT IS THE 28TH AND YK WHAT THAT MEANS? IT MEANS THAT I WILL NOW TELL YOU TO DO MATH W ME SO GET READY NOW OK FIRST KEEP THE 2 AND THEN DIVIDE THE 8 BY 2 AND WHAT DO YOU GET? EXACTLY AND YK WHAT THAT MEANS? YES US 2 WILL BE TOGETHER 4 EVER NO MATTER WHAT THATS A PROMISE <3",
    29: "IT IS NEARING THE END OF DECEMBER SO WE SHALL START A COUTNDOWN 3 DAYS TILL GOODBYE TO DECEMBER IT'S BEEN ONE HELL OF A JOURNEY BUT I'M GLAD I HAD U BY MY SIDE SO IT WAS CONSIDERABLY EASIER",
    30: "NOW NOW WE SHALL START WITH THE COUNTDOWN FIRST SO IT IS 2 DAYS TILL GOODBYE TO DECEMBER, I JUST WANT TO SAY EVEN THOUGH THIS YEAR IS ENDING MY LOVE FOR YOU HAS ONLY GROWN STRONGER DAILY HEHEHHE I LOVE YOU MWUAH",
    31: "COUNTDOWN FIRST AS USUAL SO IT IS 1 DAY TILL GOODBYE TO DECEMBER SO I'MA J LEAVE IT HERE GOODBYE DECEMBER IT WAS GREAT WHIE IT LASTED THERE MIGHT BE A LOT OF BITTERSWEET MEMORIES THROUGHOUT THE YEARS BUT ONE THING FOR SURE IS HAVING ELEJI BY MY SIDE MADE EVERYTHING EASIER AND SHE CONTRIBUTED A LOT IN THE SWEET PART WHILE LIFE ITSELF WAS LIKE DAMN I NEED TO MAKE IT BITTER AGAIN OR THIS MF WILL DIE FROM DIABETES BUT HEY AT LEAST I HAVE THE MOST STUNNING AND BEAUTIFUL AND ALSO SMART GIRL EVER I LOVE YOU BBYYY I PROMSE THAT I'LL SAY THIS AGAIN NEXT YEAR SO DO ME A FAVOR AND DON'T LEAVE ME NOR BREAK UP W ME YES? I LOVE YOU DEAR MWUAHHHH"

};

for (var i = 1; i <= 31; i++) {
    var day = document.createElement('div');
    day.classList.add('day');
    day.dataset.dayNumber = i; // Store the day number

    if (i === christmasDay && month === 12) {
        day.innerHTML = "&#127873;"; // Use HTML entity for the present emoji
        day.style.color = "red"; // Make the present icon red
    } else {
        day.innerHTML = i;
    }

    if (i > today) {
        day.classList.add('future');
        day.onclick = function() {
            var dayNumber = parseInt(this.dataset.dayNumber);
            var daysLeft = dayNumber - today;
            alert("You have to wait " + daysLeft + " days before you can open it.");
        };
    } else {
        day.onclick = function() {
            var dayNumber = parseInt(this.dataset.dayNumber);
            var note = notes[dayNumber];
            if (note) {
                alert(note);
            }
        };
    }

    // Add color to Sundays and Saturdays
    var weekday = new Date(year, month - 1, i).getDay();
    if (weekday === 0) { // Sunday
        day.style.color = "red";
    } else if (weekday === 6) { // Saturday
        day.style.color = "grey";
    }

    calendar.appendChild(day);
}
